# --- 1. DATABASE (MySQL) ---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "user123"
            - name: MYSQL_DATABASE
              value: "bus_pariwisata"
          ports:
            - containerPort: 3306
          # Database biasanya TIDAK di-autoscale sembarangan (Stateful)
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
# --- 2. BACKEND (Laravel) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  # replicas: 2  <-- KITA HAPUS BIAR HPA YANG ATUR
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: aryawrdn/backend-app:latest
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "mysql-svc"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "bus_pariwisata"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "user123"
            - name: CACHE_STORE
              value: "file"
            - name: SESSION_DRIVER
              value: "file"
          ports:
            - containerPort: 8000
          # --- WAJIB ADA UTK HPA ---
          resources:
            requests:
              cpu: "100m" # Minimal butuh segini
            limits:
              cpu: "500m" # Maksimal boleh pake segini

---
# --- 3. FRONTEND (React) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  # replicas: 2 <-- DIHAPUS JUGA
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
        - name: frontend-container
          image: aryawrdn/frontend-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # --- WAJIB ADA UTK HPA ---
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "200m"

---
# --- 4. SERVICES ---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend-app
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend-app

---
# --- 5. HPA (ROBOT SCALING) ---
# Robot Backend: Jaga CPU di 50%, Min 1 Pod, Max 5 Pod
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

---
# Robot Frontend: Jaga CPU di 50%, Min 1 Pod, Max 5 Pod
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
