# --- 1. DATABASE (MySQL) ---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "user123"
            - name: MYSQL_DATABASE
              value: "bus_pariwisata"
            # HAPUS CACHE_STORE DARI SINI (Salah tempat tadi)
          ports:
            - containerPort: 3306
---
# --- 2. BACKEND (Laravel) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: aryawrdn/backend-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "mysql-svc"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "bus_pariwisata"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "user123"
            # --- TAMBAHAN DI SINI (YANG BENAR) ---
            - name: CACHE_STORE
              value: "file"
            - name: SESSION_DRIVER
              value: "file"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend-app
---
# --- 3. FRONTEND (React) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          # PERBAIKAN: Jangan pake backend-app, tapi frontend-app
          image: aryawrdn/frontend-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend-app
